name: Build and Deploy Docs
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.4.0

      - name: Install and Build 🔧
        run: |
          yarn
          yarn bootstrap
          yarn build
          yarn docs

      - name: Deploy Docs 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: docs
          folder: docs
